In [2]:
import numpy as np
np.arange(5)

array([0, 1, 2, 3, 4])

In [4]:
r = np.arange(30).reshape(5,6)
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [5]:
r = np.arange(6).reshape(2,3)
r

array([[0, 1, 2],
       [3, 4, 5]])

In [6]:
r[-1]

array([3, 4, 5])

In [7]:
r[-1][-1]

5

In [8]:
r[-1, -1]

5

In [9]:
r[0,0]

0

In [10]:
r[1,1:]

array([4, 5])

In [11]:
r[0, :1]

array([0])

In [19]:
t = r[:1,:1]
t
t.shape
t.dtype


dtype('int32')

In [16]:
r[:,2] = 100

In [17]:
r

array([[  0,   1, 100],
       [  3,   4, 100]])

In [20]:
a = np.arange(48).reshape(2,3,2,4)
a

array([[[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23]]],


       [[[24, 25, 26, 27],
         [28, 29, 30, 31]],

        [[32, 33, 34, 35],
         [36, 37, 38, 39]],

        [[40, 41, 42, 43],
         [44, 45, 46, 47]]]])

In [21]:
a[:,0,:,-1]

array([[ 3,  7],
       [27, 31]])

In [22]:
np.loadtxt('float_data.txt')

array([[1., 2., 3., 4.],
       [3., 4., 6., 7.]])

In [23]:
np.loadtxt?


In [24]:
a = np.arange(30).reshape(5,6)

In [25]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [26]:
a % 3


array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]], dtype=int32)

In [27]:
a % 3 == 0

array([[ True, False, False,  True, False, False],
       [ True, False, False,  True, False, False],
       [ True, False, False,  True, False, False],
       [ True, False, False,  True, False, False],
       [ True, False, False,  True, False, False]])

In [28]:
a[a%3 == 0]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [29]:
a[a%3 == 0] = 0
a

array([[ 0,  1,  2,  0,  4,  5],
       [ 0,  7,  8,  0, 10, 11],
       [ 0, 13, 14,  0, 16, 17],
       [ 0, 19, 20,  0, 22, 23],
       [ 0, 25, 26,  0, 28, 29]])

In [31]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [32]:
a.sum()

15

In [33]:
a.prod()

0

In [34]:
a.mean()

2.5

In [35]:
a.std()

1.707825127659933

In [36]:
a.max()
a.min()

0

In [37]:
a.argmax()

5

In [39]:
np.unravel_index(a.argmax(), a.shape)

(1, 2)

In [40]:
a.sum(axis=0)

array([3, 5, 7])

In [41]:
a.sum(axis=1)

array([ 3, 12])

In [42]:
a


array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
#begin scipy and numpy book


In [1]:
%time
print("hello world")

Wall time: 0 ns
hello world


In [9]:
import numpy as np
arr = np.arange(1e7)
list_arr = arr.tolist()
def list_times(alist, scalar):
    for i, val in enumerate(alist):
        alist[i] = val * scalar
    return alist

%time arr * 1.1

Wall time: 36.1 ms


array([0.00000000e+00, 1.10000000e+00, 2.20000000e+00, ...,
       1.09999967e+07, 1.09999978e+07, 1.09999989e+07])

In [1]:
%time  list_times(list_arr, 1.1)

NameError: name 'list_times' is not defined

In [26]:
alist = [1, 2, 3]
arr = np.array(alist)
arr = np.zeros((5,2))
arr = np.arange(10)
arr = np.arange(1, 10)
arr = np.linspace(1,np.pi, 10)
arr = np.logspace(0,1, 5, base=10.0)
arr = np.zeros((5,5))
arr = np.zeros((2,5,5)).astype(int) + 1
arr = np.ones((2,4,3)).astype(np.float16)
arr = np.zeros(2, dtype=int)
arr = np.zeros(2, dtype=np.float32)

arr

array([0., 0.], dtype=float32)

In [31]:
arr1d = np.arange(8)
arr3d = arr1d.reshape((2,2,2))

print(arr3d)
arr1d = arr3d.ravel()
print(arr1d)
print(arr3d.shape, arr1d.shape)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[0 1 2 3 4 5 6 7]
(2, 2, 2) (8,)


In [32]:
recordarray = np.zeros((2,), dtype=('i4,f4,a10'))
toadd = [(1,2.0,'Hello'), (2, 3, "World")]
recordarray[:] = toadd

In [33]:
recordarray

array([(1, 2., b'Hello'), (2, 3., b'World')],
      dtype=[('f0', '<i4'), ('f1', '<f4'), ('f2', 'S10')])

In [42]:
recordarray = np.zeros((2,), dtype=('i4,f4,a10'))
col1 = np.arange(2) + 1
col2 = np.arange(2, dtype=np.float32)
col3 = ["Hello", "World"]
toadd = zip(col1, col2, col3)
print(toadd)
for x in toadd:
    print(x)
recordarray[:] = toadd

recordarray

(1, 0.0, 'Hello')
(2, 1.0, 'World')


TypeError: int() argument must be a string, a bytes-like object or a number, not 'zip'

In [2]:
#dir(zip)

In [43]:
alist = [[1,2],[3,4]]
alist[0][1]

2

In [44]:
arr = np.array(alist)
arr[0,1]

2

In [45]:
arr[:,1]

array([2, 4])

In [46]:
arr >1


array([[False,  True],
       [ True,  True]])

In [48]:
arr[arr>1]

array([2, 3, 4])

In [51]:
index = np.where(arr>1)
index

(array([0, 1, 1], dtype=int64), array([1, 0, 1], dtype=int64))

In [52]:
arr[index]

array([2, 3, 4])

In [53]:
data = np.empty((10,10))

In [3]:
data

NameError: name 'data' is not defined

In [55]:
np.save('test.npy', data) # np.savez slower, compressed
newdata = np.load('test.npy')

In [4]:
newdata

NameError: name 'newdata' is not defined

In [61]:
#3x + 6y − 5z = 12
#x − 3y + 2z = −2
#5x − y + 4z = 10
a = np.array([[3,6,-5],[1,-3,2],[5,-1,4]])
b = np.array([[12], [-2], [10]])
#AX = B
A = np.matrix(a)
B = np.matrix(b)
#A' invert should exist, linalg.svd
X = A**(-1)*B
X

matrix([[1.75],
        [1.75],
        [0.75]])

In [63]:
b.reshape(1,3)

array([[12, -2, 10]])

In [64]:
x = np.linalg.inv(a).dot(b)
x

array([[1.75],
       [1.75],
       [0.75]])

In [65]:
A.T

matrix([[ 3,  1,  5],
        [ 6, -3, -1],
        [-5,  2,  4]])

In [66]:
a.T

array([[ 3,  1,  5],
       [ 6, -3, -1],
       [-5,  2,  4]])

In [67]:
A.transpose()

matrix([[ 3,  1,  5],
        [ 6, -3, -1],
        [-5,  2,  4]])