In [1]:
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import scipy

In [2]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
b = np.array([4,5,6,7])
b

array([4, 5, 6, 7])

In [4]:
a * b

array([ 4, 10, 18, 28])

In [5]:
a.dot(b)

60

In [6]:
 a + b

array([ 5,  7,  9, 11])

In [7]:
a / b

array([0.25      , 0.4       , 0.5       , 0.57142857])

In [8]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [1]:
plt.plot(a, np.sin(a))

NameError: name 'plt' is not defined

In [12]:
a * 5

array([ 5, 10, 15, 20])

In [2]:
x = np.linspace(0, 2 * np.pi, 50)
plt.plot(np.sin(x))
plt.plot(np.sin(2*x))

NameError: name 'np' is not defined

In [3]:
plt.plot(x, np.sin(x), 'r-^')

NameError: name 'plt' is not defined

In [4]:
y = np.sin(x)
plt.scatter(x,y)

NameError: name 'np' is not defined

In [5]:
x = np.random.rand(200)
y = np.random.rand(200)
size = np.random.rand(200) * 30
color = np.random.rand(200)
plt.scatter(x, y, size, color)
plt.colorbar()

NameError: name 'np' is not defined

In [6]:
plt.plot(a)

NameError: name 'plt' is not defined

In [29]:
plt.figure()

<Figure size 432x288 with 0 Axes>

<Figure size 432x288 with 0 Axes>

In [30]:
plt.figure?


In [7]:
plt.subplot(2,1,1)
plt.plot(a)
plt.subplot(2,1,2)
plt.plot(b)

NameError: name 'plt' is not defined

In [8]:
plt.cla()

NameError: name 'plt' is not defined

In [9]:
f, axes = plt.subplots(2, 2)

NameError: name 'plt' is not defined

In [10]:
from scipy.misc import face
img = face()
plt.imshow(img)

NameError: name 'plt' is not defined

In [11]:
img = face(True)
plt.imshow(img, cmap=mpl.cm.bone)

NameError: name 'plt' is not defined

In [55]:
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [56]:
type(a)

numpy.ndarray

In [57]:
a.dtype

dtype('int32')

In [58]:
a.itemsize

4

In [60]:
a.shape

(4,)

In [61]:
a = np.r_[3, [0]*5, -1:1:10j]
a

array([ 3.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        , -1.        , -0.77777778, -0.55555556, -0.33333333,
       -0.11111111,  0.11111111,  0.33333333,  0.55555556,  0.77777778,
        1.        ])

In [74]:
a = np.r_[[[2],[3]],[[1],[4]]]
a

array([[2],
       [3],
       [1],
       [4]])

In [71]:
a = np.c_[3, 0, 4, 5]
a

array([[3, 0, 4, 5]], dtype=int32)

In [72]:
a = np.c_[[2,3],[1,2],[4,5]]
a

array([[2, 1, 4],
       [3, 2, 5]])

In [80]:
a = np.mgrid[0:5,0:2,0:3]
a.shape

(3, 5, 2, 3)

In [81]:
np.mgrid


In [82]:
from numpy import poly1d
p = poly1d([3,4,5])

In [84]:
print(p)

   2
3 x + 4 x + 5


In [85]:
print(p*p)

   4      3      2
9 x + 24 x + 46 x + 40 x + 25


In [86]:
print(p.deriv())

 
6 x + 4


In [87]:
print(p.integ(k=6))

   3     2
1 x + 2 x + 5 x + 6


In [88]:
p([4,5,1])

array([ 69, 100,  12])

In [90]:
x = np.r_[-2:3]
x

array([-2, -1,  0,  1,  2])

In [91]:
np.select([x > 3, x >=0], [0, x+2])


array([0, 0, 2, 3, 4])

In [93]:
f = scipy.special.factorial(3) # replace scipy.misc
f

array(6.)

In [94]:
scipy.special.comb?

In [97]:
c = scipy.special.comb(5,2)
c

10.0

In [100]:
scipy.special.lena? # already removed

Object `scipy.special.lena` not found.


In [103]:
scipy.misc.central_diff_weights?

In [12]:
#scipy.special  special functions
#help(scipy.special)

In [109]:
scipy.__version__

'1.1.0'

In [13]:
import scipy.integrate
#help(scipy.integrate)

In [14]:
import scipy.optimize
#help(scipy.optimize)

In [112]:
from scipy.optimize import minimize

In [114]:
def rosen(x):
    """ The Rosenbrock function"""
    return sum(100.0*(x[1:] - x[:-1]**2)**2 + (1-x[:-1])**2)

x0 = np.array([1.3, 0.7, 0.8, 1.9, 1.2])

res = minimize(rosen, x0, method='nelder-mead', options={'xtol':1e-8, 'disp':True})

print(res.x)

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 339
         Function evaluations: 571
[1. 1. 1. 1. 1.]


In [15]:
#help(minimize)

In [120]:
res = minimize(rosen, x0, method='powell', options={'xtol':1e-8, 'disp':True})

print(res.x)

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 19
         Function evaluations: 1622
[1. 1. 1. 1. 1.]


In [126]:
#Broyden-Fletcher-Goldfarb-Shanno algorithm (method='BFGS')  with gradient
def rosen_der(x):
    xm = x[1:-1]
    xm_m1 = x[:-2]
    xm_p1 = x[2:]
    der = np.zeros_like(x)
    der[1:-1] = 200*(xm - xm_m1**2) - 400*(xm_p1 - xm**2)*xm - 2*(1-xm)
    der[0] = -400*x[0]*(x[1]-x[0]**2) - 2*(1-x[0])
    der[-1] = 200*(x[-1]-x[-2]**2)
    return der

res = minimize(rosen, x0, method='BFGS', jac=rosen_der, options={'disp':True})
print(res.x)

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 25
         Function evaluations: 30
         Gradient evaluations: 30
[1.00000004 1.0000001  1.00000021 1.00000044 1.00000092]


In [127]:
def rosen_hess(x):
    x = np.asarray(x)
    H = np.diag(-400*x[:-1],1) - np.diag(400*x[:-1],-1)
    diagonal = np.zeros_like(x)
    diagonal[0] = 1200*x[0]**2-400*x[1]+2
    diagonal[-1] = 200
    diagonal[1:-1] = 202 + 1200*x[1:-1]**2 - 400*x[2:]
    H = H + np.diag(diagonal)
    return H

In [128]:
res = minimize(rosen, x0, method='Newton-CG',
               jac=rosen_der, hess=rosen_hess,
               options={'xtol': 1e-8, 'disp': True})

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 24
         Function evaluations: 33
         Gradient evaluations: 56
         Hessian evaluations: 24


In [129]:
def rosen_hess_p(x, p):
    x = np.asarray(x)
    Hp = np.zeros_like(x)
    Hp[0] = (1200*x[0]**2 - 400*x[1] + 2)*p[0] - 400*x[0]*p[1]
    Hp[1:-1] = -400*x[:-2]*p[:-2]+(202+1200*x[1:-1]**2-400*x[2:])*p[1:-1] \
               -400*x[1:-1]*p[2:]
    Hp[-1] = -400*x[-2]*p[-2] + 200*p[-1]
    return Hp

In [130]:
res = minimize(rosen, x0, method='Newton-CG',
               jac=rosen_der, hessp=rosen_hess_p,
               options={'xtol': 1e-8, 'disp': True})
res.x

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 24
         Function evaluations: 33
         Gradient evaluations: 56
         Hessian evaluations: 66


array([1.        , 1.        , 1.        , 0.99999999, 0.99999999])

In [131]:
res = minimize(rosen, x0, method='trust-ncg',
               jac=rosen_der, hess=rosen_hess,
               options={'gtol': 1e-8, 'disp': True})

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 20
         Function evaluations: 21
         Gradient evaluations: 20
         Hessian evaluations: 19


In [133]:
res = minimize(rosen, x0, method='trust-ncg',
               jac=rosen_der, hessp=rosen_hess_p,
               options={'gtol': 1e-8, 'disp': True})
res.x

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 20
         Function evaluations: 21
         Gradient evaluations: 20
         Hessian evaluations: 0


array([1., 1., 1., 1., 1.])

In [16]:
res = minimize(rosen, x0, method='trust-krylov',
               jac=rosen_der, hess=rosen_hess,
               options={'gtol': 1e-8, 'disp': True})
res.x

NameError: name 'minimize' is not defined

In [17]:
res = minimize(rosen, x0, method='trust-krylov',
               jac=rosen_der, hessp=rosen_hess_p,
               options={'gtol': 1e-8, 'disp': True})
res.x

NameError: name 'minimize' is not defined

In [136]:
res = minimize(rosen, x0, method='trust-exact',
               jac=rosen_der, hess=rosen_hess,
               options={'gtol': 1e-8, 'disp': True})
res.x

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 13
         Function evaluations: 14
         Gradient evaluations: 13
         Hessian evaluations: 14


array([1., 1., 1., 1., 1.])

In [18]:
from scipy.interpolate import interp1d
x = np.linspace(0, 10, num=11, endpoint=True)
y = np.cos(-x**2/9.0)
f = interp1d(x,y)
f2 = interp1d(x, y, kind='cubic')

xnew = np.linspace(0, 10, num=41, endpoint=True)
ynew = np.cos(-xnew**2/9.0)
import matplotlib.pyplot as plt
plt.plot(x, y, 'o', xnew, f(xnew), '-', xnew, f2(xnew), '--', xnew, ynew, '+')
plt.legend(['data', 'linear', 'cubic', 'origin'], loc='best')
plt.show()



NameError: name 'np' is not defined

In [19]:
x = np.linspace(0, 10, num=11, endpoint=True)
y = np.cos(-x**2/9.0)
f1 = interp1d(x, y, kind='nearest')
f2 = interp1d(x, y, kind='previous')
f3 = interp1d(x, y, kind='next')

xnew = np.linspace(0, 10, num=1001, endpoint=True)
import matplotlib.pyplot as plt
plt.plot(x, y, 'o')
plt.plot(x, y, 'o', xnew, f1(xnew), '-', xnew, f2(xnew), '--', xnew, f3(xnew), ':')
plt.legend(['data', 'nearest', 'previous', 'next'], loc='best')
plt.show()

NameError: name 'np' is not defined

In [20]:
def func(x, y):
    return x*(1-x)*np.cos(4*np.pi*x) * np.sin(4*np.pi*y**2)**2

grid_x, grid_y = np.mgrid[0:1:100j, 0:1:200j]

points = np.random.rand(1000, 2)
values = func(points[:,0], points[:,1])

from scipy.interpolate import griddata
grid_z0 = griddata(points, values, (grid_x, grid_y), method='nearest')
grid_z1 = griddata(points, values, (grid_x, grid_y), method='linear')
grid_z2 = griddata(points, values, (grid_x, grid_y), method='cubic')

import matplotlib.pyplot as plt
plt.subplot(221)
plt.imshow(func(grid_x, grid_y).T, extent=(0,1,0,1), origin='lower')
#plt.plot(points[:,0], points[:,1], 'k.', ms=1)
plt.title('Original')
plt.subplot(222)
plt.imshow(grid_z0.T, extent=(0,1,0,1), origin='lower')
plt.title('Nearest')
plt.subplot(223)
plt.imshow(grid_z1.T, extent=(0,1,0,1), origin='lower')
plt.title('Linear')
plt.subplot(224)
plt.imshow(grid_z2.T, extent=(0,1,0,1), origin='lower')
plt.title('Cubic')
plt.gcf().set_size_inches(6, 6)
plt.show()

NameError: name 'np' is not defined

In [5]:
from scipy import stats
from scipy.stats import norm
from __future__ import print_function


In [21]:
#scipy.info(stats)

In [7]:
dist_continu = [d for d in dir(stats) if
                isinstance(getattr(stats, d), stats.rv_continuous)]
dist_discrete = [d for d in dir(stats) if
                 isinstance(getattr(stats, d), stats.rv_discrete)]
print('number of continuous distributions: %d' % len(dist_continu))

print('number of discrete distributions:   %d' % len(dist_discrete))

print()


number of continuous distributions: 98
number of discrete distributions:   13


In [8]:
print(dist_continu)

['alpha', 'anglit', 'arcsine', 'argus', 'beta', 'betaprime', 'bradford', 'burr', 'burr12', 'cauchy', 'chi', 'chi2', 'cosine', 'crystalball', 'dgamma', 'dweibull', 'erlang', 'expon', 'exponnorm', 'exponpow', 'exponweib', 'f', 'fatiguelife', 'fisk', 'foldcauchy', 'foldnorm', 'frechet_l', 'frechet_r', 'gamma', 'gausshyper', 'genexpon', 'genextreme', 'gengamma', 'genhalflogistic', 'genlogistic', 'gennorm', 'genpareto', 'gilbrat', 'gompertz', 'gumbel_l', 'gumbel_r', 'halfcauchy', 'halfgennorm', 'halflogistic', 'halfnorm', 'hypsecant', 'invgamma', 'invgauss', 'invweibull', 'johnsonsb', 'johnsonsu', 'kappa3', 'kappa4', 'ksone', 'kstwobign', 'laplace', 'levy', 'levy_l', 'levy_stable', 'loggamma', 'logistic', 'loglaplace', 'lognorm', 'lomax', 'maxwell', 'mielke', 'moyal', 'nakagami', 'ncf', 'nct', 'ncx2', 'norm', 'norminvgauss', 'pareto', 'pearson3', 'powerlaw', 'powerlognorm', 'powernorm', 'rayleigh', 'rdist', 'recipinvgauss', 'reciprocal', 'rice', 'semicircular', 'skewnorm', 't', 'trapz', 'tr

In [9]:
print(dist_discrete)

['bernoulli', 'binom', 'boltzmann', 'dlaplace', 'geom', 'hypergeom', 'logser', 'nbinom', 'planck', 'poisson', 'randint', 'skellam', 'zipf']


In [22]:
#help(norm.stats)

In [14]:
norm.cdf(0) # cumulative Distribution Function 0.5
norm.cdf(8)

0.9999999999999993

In [15]:
norm.cdf([-1, 0, 1])

array([0.15865525, 0.5       , 0.84134475])

In [16]:
norm.mean(), norm.var(), norm.std()

(0.0, 1.0, 1.0)

In [17]:
norm.stats() # paramter moments='mv' m-> mean, v-> variance  原点矩

(array(0.), array(1.))

In [25]:
norm.pdf(1), norm.pdf(np.inf), norm.pdf(-np.inf) # probability density function

(0.24197072451914337, 0.0, 0.0)

In [30]:
norm.ppf(0), norm.ppf(1), norm.ppf(0.24197072451914337), norm.ppf(0.5)

(-inf, inf, -0.6999773509978507, 0.0)

In [45]:
a = norm.rvs(size=1000)
#a

In [46]:
#dir(a)
a.mean(), a.std(), a.var()

(0.0008923427510743949, 1.0057835250783098, 1.0116004993189511)

In [47]:
norm.stats(loc=3, scale=4, moments="mv")

(array(3.), array(16.))

In [23]:
#help(norm.rvs)
a = norm.rvs(loc=1, scale=4, size=1000)
a.mean(), a.var(), a.std()

NameError: name 'norm' is not defined

In [52]:
b = (a-1)/4.0
b.mean(), b.var(), b.std()

(-0.052918982382122906, 0.9489897566463227, 0.9741610527250217)

In [53]:
from scipy.stats import expon
expon.mean(scale=3.)

3.0

In [54]:
from scipy.stats import uniform
uniform.cdf([0, 1, 2, 3, 4, 5], loc=1, scale=4)

array([0.  , 0.  , 0.25, 0.5 , 0.75, 1.  ])

In [59]:
uniform.cdf([0,1,2,3,4,5], loc=1, scale =2)

array([0. , 0. , 0.5, 1. , 1. , 1. ])

In [61]:
#shape parameters
from scipy.stats import gamma
gamma.numargs,gamma.shapes

(1, 'a')

In [62]:
gamma(a=1,scale=2.0).stats(moments="mv") # the exponential distribution

(array(2.), array(4.))

In [63]:
rv = gamma(1, scale=2) # freezing Distribution
rv.mean(), rv.std()

(2.0, 2.0)

In [24]:
#help(stats.t)

In [25]:
#help(stats.chisquare)

In [68]:
np.random.seed(282629734)
x = stats.t.rvs(10, size=1000)
x.min(), x.max(), x.mean(), x.var()

(-3.7897557242248197,
 5.263277329807165,
 0.014061066398468422,
 1.288993862079285)

In [72]:
m, v, s, k = stats.t.stats(10, moments='mvsk')
m, v, s, k

(array(0.), array(1.25), array(0.), array(1.))

In [73]:
n, (smin,smax), sm, sv, ss, sk = stats.describe(x)
n, (smin,smax), sm, sv, ss, sk

(1000,
 (-3.7897557242248197, 5.263277329807165),
 0.014061066398468422,
 1.2902841462255106,
 0.21652778283120955,
 1.055594041706331)

In [74]:
stats.ttest_1samp(x, m)

Ttest_1sampResult(statistic=0.39144935201466907, pvalue=0.6955485968932746)

In [76]:
tt = (sm-m)/np.sqrt(sv/float(n))  # t-statistic for mean
pval = stats.t.sf(np.abs(tt), n-1)*2  # two-sided pvalue = Prob(abs(t)>tt)
tt, pval

(0.39144935201466907, 0.6955485968932746)

In [77]:
stats.kstest(x, 't', (10,)) # Kolmogorov-Smirnov test

KstestResult(statistic=0.01597048315646199, pvalue=0.9606358146241762)

In [78]:
stats.kstest(x, 'norm') # standard normal distribution

KstestResult(statistic=0.028315793880653972, pvalue=0.39485757274432154)

In [79]:
stats.skewtest(x), stats.kurtosistest(x), stats.normaltest(x)

(SkewtestResult(statistic=2.7846411274334515, pvalue=0.0053586995736829915),
 KurtosistestResult(statistic=4.756501829311916, pvalue=1.9697645500378176e-06),
 NormaltestResult(statistic=30.378535860841446, pvalue=2.5315397653922047e-07))

In [80]:
stats.normaltest((x-x.mean())/x.std())

NormaltestResult(statistic=30.378535860841417, pvalue=2.5315397653922386e-07)

In [81]:
#Comparing two samples
rvs1 = stats.norm.rvs(loc=5, scale=10, size=500)
rvs2 = stats.norm.rvs(loc=5, scale=10, size=500)

stats.ttest_ind(rvs1, rvs2)

Ttest_indResult(statistic=0.1050050642996483, pvalue=0.9163928897475034)

In [82]:
rvs3 = stats.norm.rvs(loc=8, scale=10, size=500)
stats.ttest_ind(rvs1, rvs3)

Ttest_indResult(statistic=-5.63829996399945, pvalue=2.2348789362243764e-08)

In [83]:
stats.norm.fit(rvs3), stats.norm.fit(rvs2), stats.norm.fit(rvs1)

((8.222476190075213, 9.994618579432784),
 (4.705957949114266, 9.882391302440517),
 (4.769873172527066, 9.33904749147327))

In [84]:
stats.ks_2samp(rvs1, rvs2), stats.ks_2samp(rvs1, rvs3), stats.ks_2samp(rvs2, rvs3)

(Ks_2sampResult(statistic=0.05600000000000001, pvalue=0.4031026070200796),
 Ks_2sampResult(statistic=0.17600000000000005, pvalue=2.925670055759639e-07),
 Ks_2sampResult(statistic=0.15399999999999997, pvalue=1.169856752862886e-05))

In [85]:
x1 = np.array([-7, -5, 1, 4, 5], dtype=np.float)
kde1 = stats.gaussian_kde(x1)
kde2 = stats.gaussian_kde(x1, bw_method='silverman')
kde1, kde2

(<scipy.stats.kde.gaussian_kde at 0x1bc83a10048>,
 <scipy.stats.kde.gaussian_kde at 0x1bc839b97f0>)

In [26]:
fig = plt.figure()
ax = fig.add_subplot(111)
ax.plot(x1, np.zeros(x1.shape), 'b+', ms=20) # rug plot
x_eval = np.linspace(-10, 10, num=200)
ax.plot(x_eval, kde1(x_eval), 'k-', label="Scott's Rule")
ax.plot(x_eval, kde2(x_eval), 'r-', label="Silverman's Rule")
plt.show()

NameError: name 'plt' is not defined

In [27]:
def my_kde_bandwidth(obj, fac=1./5):
    """We use Scott's Rule, multipied by a constant factor"""
    return np.power(obj.n, -1./(obj.d+4)) * fac

fig = plt.figure()
ax = fig.add_subplot(111)
ax.plot(x1, np.zeros(x1.shape), 'b+', ms=20) # rug plot
kde3 = stats.gaussian_kde(x1, bw_method=my_kde_bandwidth)
ax.plot(x_eval, kde3(x_eval), 'g-', label="With smaller BW")
plt.show()

NameError: name 'plt' is not defined

In [28]:
np.random.seed(12456)
x1 = np.random.normal(size=200)  # random data, normal distribution
xs = np.linspace(x1.min()-1, x1.max()+1, 200)

kde1 = stats.gaussian_kde(x1)
kde2 = stats.gaussian_kde(x1, bw_method='silverman')

fig = plt.figure(figsize=(8, 6))

ax1 = fig.add_subplot(211)
ax1.plot(x1, np.zeros(x1.shape), 'b+', ms=12)  # rug plot
ax1.plot(xs, kde1(xs), 'k-', label="Scott's Rule")
ax1.plot(xs, kde2(xs), 'b-', label="Silverman's Rule")
ax1.plot(xs, stats.norm.pdf(xs), 'r--', label="True PDF")

ax1.set_xlabel('x')
ax1.set_ylabel('Density')
ax1.set_title("Normal (top) and Student's T$_{df=5}$ (bottom) distributions")
ax1.legend(loc=1)

x2 = stats.t.rvs(5, size=200)  # random data, T distribution
xs = np.linspace(x2.min() - 1, x2.max() + 1, 200)

kde3 = stats.gaussian_kde(x2)
kde4 = stats.gaussian_kde(x2, bw_method='silverman')

ax2 = fig.add_subplot(212)
ax2.plot(x2, np.zeros(x2.shape), 'b+', ms=12)  # rug plot
ax2.plot(xs, kde3(xs), 'k-', label="Scott's Rule")
ax2.plot(xs, kde4(xs), 'b-', label="Silverman's Rule")
ax2.plot(xs, stats.t.pdf(xs, 5), 'r--', label="True PDF")

ax2.set_xlabel('x')
ax2.set_ylabel('Density')

plt.show()

NameError: name 'np' is not defined

In [29]:
# bimodal 
from functools import partial
loc1, scale1, size1 = (-2, 1, 175)
loc2, scale2, size2 = (2, 0.2, 50)
x2 = np.concatenate([np.random.normal(loc=loc1, scale=scale1, size=size1),
                     np.random.normal(loc=loc2, scale=scale2, size=size2)])

x_eval = np.linspace(x2.min() - 1, x2.max() + 1, 500)

kde = stats.gaussian_kde(x2)
kde2 = stats.gaussian_kde(x2, bw_method='silverman')
kde3 = stats.gaussian_kde(x2, bw_method=partial(my_kde_bandwidth, fac=0.2))
kde4 = stats.gaussian_kde(x2, bw_method=partial(my_kde_bandwidth, fac=0.5))

pdf = stats.norm.pdf
bimodal_pdf = pdf(x_eval, loc=loc1, scale=scale1) * float(size1) / x2.size + \
              pdf(x_eval, loc=loc2, scale=scale2) * float(size2) / x2.size


fig = plt.figure(figsize=(8, 6))
ax = fig.add_subplot(111)

ax.plot(x2, np.zeros(x2.shape), 'b+', ms=12)
ax.plot(x_eval, kde(x_eval), 'k-', label="Scott's Rule")
ax.plot(x_eval, kde2(x_eval), 'b-', label="Silverman's Rule")
ax.plot(x_eval, kde3(x_eval), 'g-', label="Scott * 0.2")
ax.plot(x_eval, kde4(x_eval), 'c-', label="Scott * 0.5")
ax.plot(x_eval, bimodal_pdf, 'r--', label="Actual PDF")

ax.set_xlim([x_eval.min(), x_eval.max()])
ax.legend(loc=2)
ax.set_xlabel('x')
ax.set_ylabel('Density')
plt.show()


NameError: name 'np' is not defined

In [30]:
# Multivariate estimation
def measure(n):
    """Measurement model, return two coupled measurements."""
    m1 = np.random.normal(size=n)
    m2 = np.random.normal(scale=0.5, size=n)
    return m1+m2, m1-m2

m1, m2 = measure(2000)
xmin = m1.min()
xmax = m1.max()
ymin = m2.min()
ymax = m2.max()

X, Y = np.mgrid[xmin:xmax:100j, ymin:ymax:100j]
positions = np.vstack([X.ravel(), Y.ravel()])
values = np.vstack([m1, m2])
kernel = stats.gaussian_kde(values)
Z = np.reshape(kernel.evaluate(positions).T, X.shape)

fig = plt.figure(figsize=(8, 6))
ax = fig.add_subplot(111)

ax.imshow(np.rot90(Z), cmap=plt.cm.gist_earth_r,
          extent=[xmin, xmax, ymin, ymax])
ax.plot(m1, m2, 'k.', markersize=2)

ax.set_xlim([xmin, xmax])
ax.set_ylim([ymin, ymax])

plt.show()

NameError: name 'np' is not defined

In [31]:
from scipy.ndimage import correlate
#help(correlate)

In [5]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
correlate(a, [1, 2.5])

array([ 0,  2,  6,  9, 13, 16, 20, 23, 27, 30])

In [97]:

a,correlate(a, [1, 2.5], output=np.float64)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 0. ,  2.5,  6. ,  9.5, 13. , 16.5, 20. , 23.5, 27. , 30.5]))

In [ ]:
a,correlate(a, [1, 2.5], output=np.float64, origin = -1) # 1 will cause python crash

In [1]:
#====================================================================#

In [2]:
import numpy as np
from scipy import linalg
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [3]:
linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [4]:
A.dot(linalg.inv(A))

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [6]:
b = A.T
b

array([[1, 3],
       [2, 4]])

In [9]:
A = np.array([[1,3,5], [2,5,1],[2,3,8]])
A

array([[1, 3, 5],
       [2, 5, 1],
       [2, 3, 8]])

In [10]:
linalg.inv(A)

array([[-1.48,  0.36,  0.88],
       [ 0.56,  0.08, -0.36],
       [ 0.16, -0.12,  0.04]])

In [11]:
A.dot(linalg.inv(A))

array([[ 1.00000000e+00, -1.11022302e-16, -6.24500451e-17],
       [ 3.05311332e-16,  1.00000000e+00,  1.87350135e-16],
       [ 2.22044605e-16, -1.11022302e-16,  1.00000000e+00]])

In [13]:
#  x + 3y + 5z = 10
# 2x + 5y + z = 8
# 2x + 3y + 8z = 3

A = np.array([[1,3,5],[2,5,1],[2,3,8]])
b = np.array([[10], [8], [3]])
linalg.solve(A, b)

array([[-9.28],
       [ 5.16],
       [ 0.76]])

In [14]:
linalg.inv(A).dot(b)

array([[-9.28],
       [ 5.16],
       [ 0.76]])

In [15]:
A = np.array([[1,3,5],[2,5,1],[2,3,8]])
#行列式 Determinant
linalg.det(A)

-25.000000000000004

In [17]:
#Computing norms 范数
# singular values 奇异值
import numpy as np
from scipy import linalg
A=np.array([[1,2],[3,4]])
norm_default = linalg.norm(A)
norm_fro = linalg.norm(A,'fro') # frobenius norm is the default
norm_1 = linalg.norm(A,1) # L1 norm (max column sum)
norm_m1 = linalg.norm(A,-1)
norm_if = linalg.norm(A,np.inf) # L inf norm (max row sum)
A, norm_default, norm_fro, norm_1, norm_m1, norm_if

(array([[1, 2],
        [3, 4]]), 5.477225575051661, 5.477225575051661, 6.0, 4.0, 7.0)

In [20]:
xi = np.arange(11)
xi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
xi[:, np.newaxis]

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [22]:
import numpy as np
from scipy import linalg
import matplotlib.pyplot as plt


In [23]:
c1,c2 = 5.0, 2.0
i = np.r_[1:11]

xi = 0.1*i
yi = c1*np.exp(-xi) + c2*xi
zi = yi + 0.05*np.max(yi) * np.random.randn(len(yi))

In [24]:
xi,yi,zi

(array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]),
 array([4.72418709, 4.49365377, 4.3040911 , 4.15160023, 4.0326533 ,
        3.94405818, 3.88292652, 3.84664482, 3.8328483 , 3.83939721]),
 array([5.06519632, 4.35606362, 4.33627876, 4.35872683, 3.92916187,
        3.93583114, 3.65385417, 3.94580423, 3.82105187, 3.63126389]))

In [25]:
np.random.randn(len(yi))

array([-0.71282124,  0.35413556, -0.03574071, -0.03329815, -0.51618242,
        0.35766351,  2.34326441,  0.93678993,  0.37661115,  0.30963138])

In [26]:
A = np.c_[np.exp(-xi)[:, np.newaxis], xi[:, np.newaxis]]

In [27]:
A

array([[0.90483742, 0.1       ],
       [0.81873075, 0.2       ],
       [0.74081822, 0.3       ],
       [0.67032005, 0.4       ],
       [0.60653066, 0.5       ],
       [0.54881164, 0.6       ],
       [0.4965853 , 0.7       ],
       [0.44932896, 0.8       ],
       [0.40656966, 0.9       ],
       [0.36787944, 1.        ]])

In [28]:
c, resid, rank, sigma = linalg.lstsq(A, zi)

In [29]:
c

array([5.17860742, 1.80241955])

In [30]:
xi2 = np.r_[0.1:1.0:100j]
yi2 = c[0]*np.exp(-xi2) + c[1]*xi2

In [32]:
xi2, yi2

NameError: name 'xi2' is not defined

In [33]:
plt.plot(xi,zi,'x', xi2, yi2)
plt.axis([0,1.1,3.0,5.5])
plt.xlabel('$x_i$')
plt.title('Data fitting with linalg.lstsq')
plt.show()

NameError: name 'plt' is not defined

In [33]:
A = np.array([[1,5,2],[2,4,1],[3,6,2]])
A

array([[1, 5, 2],
       [2, 4, 1],
       [3, 6, 2]])

In [35]:
val, vec = linalg.eig(A)
val, vec

(array([ 7.9579162 +0.j, -1.25766471+0.j,  0.2997485 +0.j]),
 array([[-0.5297175 , -0.90730751,  0.28380519],
        [-0.44941741,  0.28662547, -0.39012063],
        [-0.71932146,  0.30763439,  0.87593408]]))

In [39]:
np.sum(abs(vec**2), axis = 0) # ||v||**2   = sum(vi)**2 = 1(i = ...)

array([1., 1., 1.])

In [43]:
vec1 = np.array(vec[:, 0]).T
vec1, A.dot(vec1) - val[0] * vec1

(array([-0.5297175 , -0.44941741, -0.71932146]),
 array([-2.66453526e-15+0.j, -4.44089210e-16+0.j, -1.77635684e-15+0.j]))